name_admin: "Quan Van Chung"
length:
  min_5: 5
  min_8: 8
  max_100: 100
  max_250: 250
  lenth_max: 300
email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
gravatar:
  small_size: 50
  medium_size: 80
per_page: 15
