name_admin: "Quan Van Chung"
length:
  lenth_min: 5
  min_5: 5
  min_8: 8
  max_100: 100
  max_250: 250
  lenth_max: 300
email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
gravatar:
  small_size: 50
  medium_size: 80
  max_size: 200
per_page: 10
per_page_food: 9
page_per_min: 3
page_per_medium: 5
open: "badge-primary"
confirmed: "badge-info"
shipping: "badge-secondary"
completed: "badge-success"
cancelled: "badge-danger"
button: [ {name: btn-primary}, {name: btn-info}, {name: btn-secondary},
          {name: btn-success}, {name: btn-danger}]
image:
  size_1mb: 5
  format: ["image/png", "image/jpg", "image/jpeg"]
resize_images: "300x300!"
resize_thumbnail: "80x80!"
resize_thumbnail_max: "250x250!"
out_of_stock: 0
quantity_min: 1
